apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v1
spec:
  replicas: 4   # 80% traffic (more pods)
  selector:
    matchLabels:
      app: sample-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-app
        version: v1
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/
          name: html
      volumes:
      - name: html
        configMap:
          name: sample-app-html
